### PR TITLE
Adding colormap apricity

### PR DESCRIPTION
**Pull request by matthewturk**
Apricity is an "obsolete" word meaning the warmth of the Sun in winter.  This colormap is pretty, and was designed with viscm to embody that feeling.

galaxy0030_Projection_z_density

### CODE REVIEW

**Comment by neutrinoceros** [comment]
Looks like I never got around deploying useful infrastructure for image test _reports_. Let me know if you need a hand

**Comment by neutrinoceros** [comment]
closing/reopening to trigger a fresh job

**Comment by neutrinoceros** [comment]
btw you should add yourself to `CREDITS`

**Comment by matthewturk** [comment]
I'm not in it already?!  I made at least one of the other colormaps!

**Comment by neutrinoceros** [comment]
Oh, yes you are, for `octarine`, but you could still update the file to mention `apricity` too !

**Comment by neutrinoceros** [comment]
@matthewturk need a hand ?

**Comment by matthewturk** [comment]
I'd love a hand.  But I can also give it a go and try to get through it.
;-)

**Comment by chummels** [comment]
I like it!

**Comment by neutrinoceros** [comment]
I finally wrote some documentation for this process here : https://github.com/yt-project/yt/pull/4418

The workflow is similar in `cymt`, but simpler: there isn't a git submodule involved (everything is in the same repo), so only one PR (this one) is needed. `cmyt`'s baseline is found in `tests/baseline`

**Comment by neutrinoceros** [comment]
... except that the new baseline didn't upload. I fixed that in #113. Closing/reopening this PR to trigger CI again

**Comment by neutrinoceros** [comment]
in fact while I'm down this rabbit hole I might as well finish this PR myself

**Pull request merged**
